#!/usr/bin/env python3
"""Build a VIEDIT target with M80 + L80 on the altairsim simulator.

This drives the `altairsim` binary through its MCP interface (see mcpdrive.py).
How it works:
  * the current sources move onto the CP/M disk with the **R** utility
    (altairsim's hostbridge card, port 0xB0), and TARGET.COM/.SYM come back with
    **W** -- no DSK-image surgery
  * it builds directly on CPM22-8MB-56K-VIEDIT.DSK (which already carries M80/L80
    and altairsim's R/W/HDIR hostbridge utilities); there is no per-build working
    copy, so the committed image always holds the current source

Default target is the real editor VIEDIT.COM.  Pass a target name to build a
test stub instead: SCRTST (screen engine) or KEYTST (key decoder).

Self-contained: sources live flat beside this file (no src/ dir), mcpdrive.py
sits alongside, and `altairsim` must be on PATH.  Run from this directory:

    python3 build_vi.py            # VIEDIT.COM
    python3 build_vi.py SCRTST     # screen-engine stub
    python3 build_vi.py KEYTST     # key-decoder stub
"""
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from mcpdrive import AltairSim, crlf

MACHINE = "viedit.toml"                                   # altairsim machine (delta on `default`)
DISK = os.path.join(HERE, "CPM22-8MB-56K-VIEDIT.DSK")     # the CP/M disk: M80/L80 + hostbridge; built on in place

# Build targets: TARGET -> link order of modules.  VI.INC / VIBLD.INC are
# INCLUDEd, not linked.  VIEND must link last (BMDEND = end of image).  VICMD's
# old monolith is split by feature into modules each small enough to edit and
# few enough that the single L80 command line stays under CP/M's ~127-char limit.
TARGETS = {
    "SCRTST": ["SCRTST", "VISCREEN", "VIBUF", "VIFILEIO", "VIWIN", "VIEND"],
    "KEYTST": ["KEYTST", "VIKEY", "VIEND"],
    "VIEDIT": ["VI", "VISCREEN", "VIKEY", "VIBUF", "VIWIN", "VIFILEIO",
               "VIVM", "VICMD", "VICMDOPS", "VICMDEXC", "VICMDSCH", "VICMDUND",
               "VICMDSUB", "VICMDDAT", "VIEND"],
}


def gen_buildstamp():
    """(Re)generate VIBLD.INC with the current timestamp.  VICMD INCLUDEs it
    to define BLDTS (printed by :stat), so the running binary's build can be
    confirmed.  Regenerated every build so the stamp is fresh."""
    ts = time.strftime("%Y-%m-%d %H:%M")
    body = ("; VIBLD.INC -- build stamp printed by :stat.  Regenerated by\n"
            "; build_vi.py on every build (M80 has no date facility).\n"
            "BLDTS:\tDB\t'%s',0\n" % ts)
    with open(os.path.join(HERE, "VIBLD.INC"), "wb") as f:
        f.write(crlf(body).encode("ascii"))
    return ts


def run_build(target):
    modules = TARGETS[target]
    ts = gen_buildstamp()
    print(f"  build stamp {ts}")

    console = []
    def cmd(c, timeout=600):
        out = sim.cmd(c, timeout=timeout)
        console.append(out)
        return out

    # Build directly on the tracked CP/M disk (no working copy): it carries
    # M80/L80 and altairsim's hostbridge R/W/HDIR utilities, and the R step
    # below refreshes it with the current sources -- so the committed image
    # always holds them and a fresh clone can mount it and SUBMIT VIEDIT.
    with AltairSim(MACHINE, cwd=HERE, disk=os.path.basename(DISK)) as sim:
        sim.boot()

        # Move every source onto the CP/M disk via R (host -> guest).
        # VI.INC / VIBLD.INC are INCLUDEd; the rest are assembled + linked.
        # VIEDIT.SUB rides along so an in-CP/M `SUBMIT VIEDIT` build works too.
        print("  R *.INC, *.MAC, VIEDIT.SUB -> CP/M disk")
        sim.rfile("*.INC")
        sim.rfile("*.MAC")
        sim.rfile("VIEDIT.SUB")

        for mod in modules:
            cmd(f"ERA {mod}.REL", timeout=60)
        for mod in modules:
            print(f"  M80 {mod}...")
            cmd(f"M80 {mod},{mod}={mod}")

        # Single-line L80.  CP/M's console input line is capped near 127 chars,
        # so the whole command must fit -- this is the constraint that bounds how
        # many modules VIEDIT may be split into.  Guard it so an over-long
        # command fails loudly here instead of being silently truncated.
        link = ",".join(modules)
        l80 = f"L80 {link},{target}/Y/N/E"
        if len(l80) > 127:
            sys.exit(f"BUILD FAILED: L80 command is {len(l80)} chars (> 127 limit).\n"
                     f"  Reduce the {target} module count (merge feature modules).\n  {l80}")
        print(f"  L80 {link},{target}/Y/N/E  [{len(l80)} chars]")
        cmd(l80)

        # Pull the artifacts back to the host via W (guest -> host).
        sim.wfile(f"{target}.COM")        # .COM implies binary
        sim.wfile(f"{target}.SYM", "T")   # symbol table is text

        # Also pull each module's M80 listing (.PRN, text) alongside the sources.
        for mod in modules:
            sim.wfile(f"{mod}.PRN", "T")

    text = "\n".join(console)
    up = text.upper()

    ok = True
    # L80 prefixes EVERY diagnostic with '%' (e.g. "%Mult. Def. Global",
    # "%Undefined Global", "%Overlapping ...").  These are warnings, not fatal --
    # L80 still writes a .COM -- so treat them all as build failures.
    warns = [ln.strip() for ln in text.splitlines() if ln.lstrip().startswith("%")]
    if warns:
        ok = False
        print("=== L80 warnings (treated as build failure) ===")
        for ln in warns:
            print("  " + ln)
    if "UNDEFINED GLOBAL" in up:
        ok = False
    for n in re.findall(r"(\d+)\s+FATAL ERROR", up):
        if int(n) > 0:
            ok = False

    com = os.path.join(HERE, f"{target}.COM")
    if os.path.exists(com) and os.path.getsize(com) > 0:
        print(f"  {target}.COM written ({os.path.getsize(com)} bytes)")
    else:
        print(f"ERROR: {target}.COM was not produced")
        ok = False

    if not ok:
        print("=== CP/M output ===")
        print(text)
        sys.exit("BUILD FAILED")

    # W already wrote {target}.COM/.SYM and each module's .PRN into this
    # directory (everything lives here now -- no separate src/ to mirror into).
    print(f"  {target}.COM, {target}.SYM and .PRN listings written here")

    print("BUILD OK")


if __name__ == "__main__":
    run_build(sys.argv[1] if len(sys.argv) > 1 else "VIEDIT")
